import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillLinkedin,AiFillYoutube} from 'react-icons/ai'
import Image from "next/image";
import png from "../public/png.png"
import dive from "../public/dive.png"
import mimic from "../public/mimic.png"
import moment from "../public/moment.png"
import faye from "../public/faye.jpg"
import kacie from "../public/kacie.jpg"
import ian from "../public/ian.jpg"
import friends from "../public/friends.jpg"
import hwasan from "../public/hwasan.jpg"
import tree from "../public/tree.jpg"
import faye2 from "../public/faye2.jpg"
import anna from "../public/anna.jpg"
import {useState} from "react";
export default function Home() {
  const[darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>David Tepeneu Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen md:text-xl">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="font-avo text-3xl md:text-5xl dark:text-white">David Tepeneu</h1>
            <ul className="flex items-center">
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl dark:text-white"/></li>
              <li>
                <a className="bg-gradient-to-r from-pink-500 to-orange-500 dark:bg-gradient-to-r dark:from-cyan-500 dark:to-teal-500 text-white px-4 py-2 rounded-md ml-8 dark:text-gray-800 dark:font-semibold" href="https://github.com/DavidTepeneu/DuhveedTeps/blob/main/Resume.pdf" target="_blank">Resume</a></li>
              <li>
              <p className="py-2 rounded-md ml-8 dark:text-gray-100 dark:font-semibold cursor-pointer" onClick={() => window.open("mailto:david.tepeneu@gmail.com?subject=Fan Mail&body=I love you <3")}>Email Me</p>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 bg-gradient-to-r from-pink-500 to-orange-500 bg-clip-text text-transparent font-medium md:text-6xl dark:bg-gradient-to-r dark:from-cyan-400 dark:to-green-300">David Tepeneu</h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-gray-200">Developer and Manager.</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-300">Computer Science Sophomore at the <span className="text-blue-500 dark:text-cyan-500 cursor-pointer" onClick={() => window.open("https://www.utdallas.edu/")}>University of Texas at Dallas</span>. I'm always looking for something new to learn :D</p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-1 text-gray-600">
            <AiFillLinkedin onClick={() => window.open('https://www.linkedin.com/in/david-tepeneu/')} className="cursor-pointer dark:text-gray-300"/>
            <AiFillYoutube  onClick={() => window.open('https://www.youtube.com/@davidtepeneu7007')} className="cursor-pointer dark:text-gray-300"/>
          </div>
          <div className="relative mx-auto shadow-2xl rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={dive} layout="fill" objectFit="cover"/>
          </div>
        </section>
        
        <section>
          <div className="py-8">
            <h3 className="text-left text-3xl dark:text-gray-200">Some of my accomplishments!</h3>
          </div>
          <div className="gap-y-2">
            <div className="shadow-2xl dark:shadow-lg dark:shadow-white p-10 rounded-xl mt-5 mb-10">
            <p className="font-semibold text-center text-md leading-8 text-gray-800 dark:text-gray-300 md:text-lg lg:text-xl">
              As a sophomore studying CS in college I have already taken the following courses CS related courses:
            </p>
            <br></br>
              <ul className="px-9 text-center text-xs lg:text-base md:text-sm">
                <li className="dark:text-gray-300 font-semibold">
                  Programming Fundamentals
                </li>
                <li className="dark:text-gray-300 font-semibold">
                  Intro to Comp Sci & Software
                </li>
                <li className="dark:text-gray-300 font-semibold">
                  Discrete Math for Computing
                </li>
                <li className="dark:text-gray-300 font-semibold">
                  Computer Science II
                </li>
                <li className="dark:text-gray-300 font-semibold">
                  Computer Architecture
                </li>
                <li className="dark:text-gray-300 font-semibold">
                  Discrete Math for Computing II
                </li>
                <li className="dark:text-gray-300 font-semibold">
                  Probability and Stats in CS
                </li>
                <li className="dark:text-gray-300 font-semibold">
                  Data Structures & Algorithm Analysis
                </li>
                <li className="dark:text-gray-300 font-semibold">
                  Software Engineering
                </li>
              </ul>
            </div>
            <div className="shadow-2xl dark:shadow-lg dark:shadow-white p-3 rounded-xl mt-5 mb-10">
              <Image id="mimicID" className="mx-auto object-fill cursor-pointer dark:text-white rounded-xl" src={mimic} onClick={() => window.open("https://github.com/acm-projects/Mimic")}/>
            </div>
            <div className="shadow-2xl dark:shadow-lg dark:shadow-white p-3 rounded-xl mt-5 mb-10">
              <Image id="momentID" className="mx-auto object-fill cursor-pointer rounded-xl" src={moment} onClick={() => window.open("https://github.com/acm-projects/In-the-Moment")}/>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-gray-200">Photography</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              I've always been interested in photography, gathering over 1 million views on  <span className="text-blue-500 cursor-pointer dark:text-cyan-500" onClick={() => window.open("https://www.google.com/maps/contrib/101698129330875079719/photos/@10.7721094,-43.0116494,2z/data=!3m1!4b1!4m3!8m2!3m1!1e1")}>google (check me out)</span> during my time in middle school alone!
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-300">
              Here are a bunch of pictures I am proud of!
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image src={faye2} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={faye} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={anna} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={kacie} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={hwasan} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={friends} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={tree} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className="basis-1/3 flex-1">
              <Image src={ian} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
